name: SingBox Proxy Updater

on:
  schedule:
    - cron: '*/59 * * * *'
  workflow_dispatch:

jobs:
  run-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Download Sing-box
      run: |
        # Скачиваем v1.12.12
        wget https://github.com/SagerNet/sing-box/releases/download/v1.12.12/sing-box-1.12.12-linux-amd64.tar.gz
        tar -xzf sing-box-1.12.12-linux-amd64.tar.gz
        # Достаем бинарник из вложенной папки
        mv sing-box-1.12.12-linux-amd64/sing-box ./sing-box
        chmod +x sing-box
        ./sing-box version

    - name: Run Logic
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        PROJ_ID: ${{ secrets.PROJ_ID }}
      run: python main.py
