name: Xray Proxy Updater

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Download Xray-core
      run: |
        # Скачиваем официальный релиз Xray
        wget https://github.com/XTLS/Xray-core/releases/download/v1.8.24/Xray-linux-64.zip
        unzip Xray-linux-64.zip
        mv xray Xray-linux-64/ # иногда xray выпадает в корень, иногда нет, но unzip обычно плоский
        # Проще найти бинарник
        if [ -f "xray" ]; then
          chmod +x xray
        else
          # Если он внутри папки после распаковки (зависит от версии релиза)
          find . -name "xray" -type f -exec mv {} . \;
          chmod +x xray
        fi
        ./xray version

    - name: Run Logic
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        PROJ_ID: ${{ secrets.PROJ_ID }}
      run: python main.py
