name: Xray Proxy Updater

on:
  schedule:
    - cron: '*/15 * * * *'  # Запуск каждые 15 минут
  workflow_dispatch:        # Кнопка ручного запуска

jobs:
  run-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Download Xray-core
      run: |
        # Скачиваем архив
        wget https://github.com/XTLS/Xray-core/releases/download/v1.8.24/Xray-linux-64.zip
        # Распаковываем (файлы появятся в текущей папке)
        unzip Xray-linux-64.zip
        # Удаляем лишнее
        rm Xray-linux-64.zip
        # Делаем исполняемым
        chmod +x xray
        # Проверяем версию (для логов)
        ./xray version

    - name: Run Logic
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        PROJ_ID: ${{ secrets.PROJ_ID }}
      run: python main.py
