name: BoxRunner Update

on:
  schedule:
    - cron: '*/15 * * * *'  # Каждые 15 минут
  workflow_dispatch:        # Ручной запуск

jobs:
  run-cycle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Libs
      run: pip install -r requirements.txt

    - name: Setup Sing-box (v1.12.12)
      run: |
        wget https://github.com/SagerNet/sing-box/releases/download/v1.12.12/sing-box-1.12.12-linux-amd64.tar.gz
        tar -xzf sing-box-1.12.12-linux-amd64.tar.gz
        mv sing-box-1.12.12-linux-amd64/sing-box ./sing-box
        chmod +x ./sing-box

    - name: Execute Logic
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        PROJ_ID: ${{ secrets.PROJ_ID }}
      run: python main.py
